### ISSUE TITLE
optimal method with exact matching on some variables

### ISSUE THREAD

**Issue by jiweihe1223** [kosukeimai/MatchIt#60] opened 2021-02-26 01:19 UTC
I used the `method = “exact”` option to force exact matching on some variables and used other methods for the other variables. 

The `method = “nearest”` approach worked as expected. However, when I tried switching the argument to `method = “optimal”`, it seems the matching id output by `match.matrix` do not show the expected matching for the variables specified in the exact option. Why is it so? 

You can see in the output, subject 2 and subject 25 who are matched do not have the same age. 

Code I used:
match= matchit(A ~ SEX + AGE + V1 + V2, method = "optimal", 
               exact  = c("SEX", "AGE"), data = data_test)
match_id<-match$match.matrix
N<-9
match_id2<-c(1:N, match_id)

match_data<-match.data(match)
#reorder matched control in the same order as treated
match_data2<-match_data[match_id2, ]
match_data2$match_id<-rep(1:N, 2)

Output:
> match_data2
   SEX AGE  V1  V2 A   distance weights subclass match_id
1    F   8 5.4 6.0 1 0.19925382       1        1        1
2    F   9 5.7 2.6 1 0.52655669       1        2        2
3    M  10 5.6 1.6 1 0.25929894       1        3        3
4    F   8 5.1 3.7 1 0.19159122       1        4        4
5    M   8 4.6 2.9 1 0.03403255       1        5        5
6    M   7 5.7 4.9 1 0.30804933       1        6        6
7    F   7 5.2 5.2 1 0.21183573       1        7        7
8    F   6 5.3 5.6 1 0.30090303       1        8        8
9    F   6 4.4 4.2 1 0.06211456       1        9        9
30   M   8 5.4 4.1 0 0.15866640       1        1        1
25   F   8 5.4 2.7 0 0.41199904       1        2        2
13   F   6 5.0 3.7 0 0.26556803       1        3        3
28   M   8 5.4 3.9 0 0.16722246       1        4        4
53   F   6 4.3 5.6 0 0.03196558       1        5        5
24   M   7 5.7 4.9 0 0.30804933       1        6        6
51   M   8 5.5 3.4 0 0.23293292       1        7        7
36   F   8 5.2 2.8 0 0.28892715       1        8        8
47   F   6 4.3 3.5 0 0.05998461       1        9        9

**Comment by ngreifer** [comment] 2021-02-26 20:30
I'm looking into this. Could you provide the full dataset so I can investigate? On the datasets I have It seems to be working correctly. When you run `summary(match)`, is the `Std. Pair Diff.` value for `AGE` different from 0?

**Comment by jiweihe1223** [comment] 2021-02-26 21:48
Thanks so much!
I attached the dataset.
I did not find the Std. Pair Diff. in the summary you mentioned.
Please let me know.

**Comment by ngreifer** [comment] 2021-02-27 01:52
Sorry, I don't see the dataset anywhere.

**Comment by jiweihe1223** [comment] 2021-02-27 02:02
I attached it in the email reply. What is the correct way of attaching the data, or do I have to paste it here?

**Comment by jiweihe1223** [comment] 2021-02-27 02:04
> data_test
   SEX AGE  V1  V2 TREAT
1    F   8 5.4 6.0     1
2    F   9 5.7 2.6     1
3    M  10 5.6 1.6     1
4    F   8 5.1 3.7     1
5    M   8 4.6 2.9     1
6    M   7 5.7 4.9     1
7    F   7 5.2 5.2     1
8    F   6 5.3 5.6     1
9    F   6 4.4 4.2     1
10   F   8 4.8 4.0     0
11   F   6 3.4 4.9     0
12   F   6 3.9 4.5     0
13   F   6 5.0 3.7     0
14   M   8 4.3 3.3     0
15   F   9 5.5 3.6     0
16   F   6 4.6 4.7     0
17   F   6 4.0 3.3     0
18   F   8 4.4 1.8     0
19   F   6 4.3 2.6     0
20   F   6 3.7 5.6     0
21   F   6 4.5 3.5     0
22   M   8 5.2 2.7     0
23   M   8 4.4 1.9     0
24   M   7 5.7 4.9     0
25   F   8 5.4 2.7     0
26   F   6 3.4 4.5     0
27   F   6 3.8 4.9     0
28   M   8 5.4 3.9     0
29   F   7 4.7 4.5     0
30   M   8 5.4 4.1     0
31   M   8 4.7 4.3     0
32   F   9 5.1 4.6     0
33   F   8 5.0 3.9     0
34   M   8 4.7 4.4     0
35   F   6 4.6 4.6     0
36   F   8 5.2 2.8     0
37   M  10 5.5 2.9     0
38   F   6 3.6 4.9     0
39   F   8 5.0 3.7     0
40   F   8 4.3 1.8     0
41   M   8 4.9 3.9     0
42   F   6 3.5 3.1     0
43   F   6 4.0 3.7     0
44   M   7 5.4 5.6     0
45   M   7 5.2 4.2     0
46   F   8 4.8 5.6     0
47   F   6 4.3 3.5     0
48   M   7 5.8 5.2     0
49   F   6 4.3 5.7     0
50   F   6 3.5 4.1     0
51   M   8 5.5 3.4     0
52   F   6 4.7 5.2     0
53   F   6 4.3 5.6     0
54   F   6 4.8 4.6     0
55   F   6 4.3 5.1     0
56   M  10 5.5 3.4     0
57   F   6 4.5 3.3     0
58   F   8 5.4 4.0     0
59   M   8 4.9 4.5     0
60   F   6 4.6 5.0     0
61   F   7 4.9 4.8     0
62   M  10 5.4 3.1     0
63   F   7 4.7 4.4     0
64   F   6 4.3 3.6     0
65   F   6 4.1 5.3     0
66   F   7 5.2 6.6     0
67   M   8 5.2 4.6     0
68   M   7 4.9 3.6     0
69   F   6 3.7 3.3     0
70   F   6 4.2 5.6     0
71   F   9 5.5 4.4     0
72   F   8 5.7 6.3     0

**Comment by ngreifer** [comment] 2021-02-27 03:07
Thank you for sending the dataset. It seems like you're using an old version of `MatchIt`. I was able to replicate your results using version 3.0.2, but not using version 4.0.0 or above. In recent versions, the units are correctly matched. Please update `MatchIt` and this should be fixed.

Please make sure you are always using the most updated version of a package. In the future, if you think you have found a bug or unexpected behavior, it may have already been fixed in an updated version, saving you and the maintainers time.

**Closed by ngreifer** 2021-02-27 03:07 UTC

**Comment by jiweihe1223** [comment] 2021-02-27 03:14
I see. I reinstalled Matchit(). It did solve the problem. Thank you so much!
Lesson learned.
